# .github/workflows/main.yml

on: push

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: 15998472+itseffi@users.noreply.github.com 
        GIT_BRANCH: main
        ORIGIN_TIMESTAMP: "1767225600"
        MAX_DAYS: 1095
        MIN_COMMITS_PER_DAY: 5
        MAX_COMMITS_PER_DAY: 10
        INCLUDE_WEEKDAYS: "true"
        INCLUDE_WEEKENDS: "true"
